author: iAliHD
description: Me derping around with my awesome skeels.
main: me.ialihd.weirdploogin2.WeirdPloogin
name: WeirdPloogin
version: 0.2
commands:
  command:
    description: Command's description.
    aliases: [aliases, for, the, command ]
